name: Toma Toe Workflow
on: [workflow_dispatch]

jobs:
  publish-bicep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile infrastructure
        uses: Azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: az bicep build --file ./deployment/main.bicep
      - name: Compile infrastructure
        uses: Azure/cli@1.0.4
        with:
          azcliversion: latest
          inlineScript: az bicep build --file ./deployment/trafficmgr.bicep
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bicep-templates
          path: deployment/*.json

  infrastructure-incremental-test:
    needs: publish-bicep
    uses: tmarcis1/github-actions-start/.github/workflows/deployment.yml@ec9090bec524180f49feb8e7040daa7691907e23
    with:
      environment: test
    secrets:
      azure-login: ${{ secrets.AZURE_TEST }}

  infrastructure-incremental-prod:
    needs: infrastructure-incremental-test
    uses: tmarcis1/github-actions-start/.github/workflows/deployment.yml@ec9090bec524180f49feb8e7040daa7691907e23
    with:
      environment: prod
    secrets:
      azure-login: ${{ secrets.AZURE_PROD }}
